### ISSUE TITLE
Conflicting style requirements in cpplint

### ISSUE THREAD

**Issue by max-krichenbauer** [git-afsantos/haros_plugins#12]
In the `cpplint` plug-in, on [line 3948](https://github.com/git-afsantos/haros_plugins/blob/7117fe682f324c6cb3300798150a5de007890ca1/haros_plugin_cpplint/plugin.py#L3948), is a check for "open curly brace should almost never be on its own line", which I believe is based on the Google C++ Style Guide (see: [functions](https://google.github.io/styleguide/cppguide.html#Function_Declarations_and_Definitions), [conditionals](https://google.github.io/styleguide/cppguide.html#Conditionals)).

On [line 4052](https://github.com/git-afsantos/haros_plugins/blob/7117fe682f324c6cb3300798150a5de007890ca1/haros_plugin_cpplint/plugin.py#L4052) however, the [ROS C++ style guide](http://wiki.ros.org/CppStyleGuide#Formatting) is enforced, which required curly braces to always be on a new line.

Thus no program can ever satisfy the checks.
One of the rules should be removed.

I provide a PR if you let me know which rule is supposed to be used.

**Comment by git-afsantos** [comment]
Yes, the tool checks for both style guides, and the idea is to allow that. Different people choose different style guides. No single style should be enforced (except for ROS 2, where you must stick with the ROS style).

Although not very well documented, [3.2.0 added support](https://github.com/git-afsantos/haros/blob/f04e11d9ab3c238f57e89e2cc782c4729b4b2789/CHANGELOG.md#320---2019-04-04) to [ignore specific rules](https://github.com/git-afsantos/haros/commit/15f3dc0f59522500b04bd12bf4fc70f8b8a9672c#diff-a107065aeff68ec4727d4fe07e9f9fcd) during analysis. So you can choose the style you like the most, and mute reports for the other one.

**Comment by max-krichenbauer** [comment]
Thank you for the explanation!
