### ISSUE TITLE
cccc_plugin ran into an error.

### ISSUE THREAD

**Issue by droter** [git-afsantos/haros_plugins#9]
I am getting an error with cccc_plugin:

$ ./haros-runner.py analyse -p my_project.yaml -d temp
[HAROS] Loading common definitions...
[HAROS] Loading plugins...
  > Loaded mi_calculator
  > Loaded cpplint_plugin
  > Loaded cppcheck_plugin
  > Loaded pylint_plugin
  > Loaded lizard_plugin
  > Loaded ccd_plugin
  > Loaded radon_plugin
  > Loaded cccc_plugin
[HAROS] Reading project and indexing source code...
[HAROS] Running analysis...
ERROR:haros.analysis_manager:Plugin cccc_plugin ran into an error.
[HAROS] Saving analysis results...

Any ideas?

Thanks in advance,

Matt

**Comment by git-afsantos** [comment]
That is a relatively recent plugin, for which I also forgot to add the dependency on the README of HAROS.

If you need the metrics provided by [CCCC](https://github.com/sarnold/cccc/), install it. It is [available](https://packages.ubuntu.com/search?keywords=cccc&searchon=names&suite=all&section=all) on Ubuntu Trusty, Xenial and Bionic, so a simple *apt-get* should suffice.

```bash
apt-get install cccc
```

If you do not need the metrics provided by CCCC, or you do not want to install it, just disable the plugin.

```bash
./haros-runner.py analyse -b cccc_plugin -p my_project.yaml -d temp
```

I will fix the README for this as well.

**Comment by git-afsantos** [comment]
Fixed with https://github.com/git-afsantos/haros/commit/a62d3b44eff355b30fed0bdbc91654bffd483c2d
